// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbwpialjbgoqvtniyhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBid3BpYWxqYmdvcXZ0bml5aGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjA5NjIsImV4cCI6MjA2MTU5Njk2Mn0.p9hQxthPYdT2k5d4wx5mafCzo9WgzEzEiMeqgSdwsSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);